version: '3.6'
services:
  server:
    build: ./server
    command: python server.py
    ports:
      - 8080:8080
  client:
    build: ./client
    command: python client.py
    depends_on: 
      - server
    environment: 
      URL: server
      PORT: 8080
